[package]
name = "merco-macros"
version = "0.1.0"
edition = "2021"
description = "Procedural macros for merco-llmproxy"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
serde_json = "1.0"
ctor = "0.2"
